# frontend/liff/nginx.conf
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Required for React Router (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
}